apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: lfs158
spec:
  rules:
  - host: jenkinskube.com
    http:
      paths:
      - backend:
          service:
            name: jenkinskube
            port: 
              number: 8080
        path: /
        pathType: ImplementationSpecific
    